### ISSUE TITLE
Keeps reverting to the old version

### ISSUE THREAD

**Issue by thatjimupnorth** [nonnonstop/sd-webui-3d-open-pose-editor#25]
I've uninstalled and reinstalled the extension and it's no longer showing the most recent updates to the UI. Keeps switching back to the original version without the Gradio controls. 

<img width="2672" alt="Screenshot 2023-03-24 at 19 54 09" src="https://user-images.githubusercontent.com/113929527/227626204-156390c5-2883-4d2d-bc3e-b2c2f5168575.png">

**Comment by nonnonstop** [comment]
@thatjimupnorth run the following command in `extensions/sd-webui-3d-open-pose-editor` directory.
```git reset --hard 4e7a400f7c42a5f9413d182413d950b2f5a58c79```

**Comment by thatjimupnorth** [comment]
Epic. Thank you. That's fixed it now. Any idea what caused it so I can fix it myself in future?

**Comment by nonnonstop** [comment]
See #19.
Due to limitations of Gradio bindings, we decided to use the controller of the original version.

In the latest version, the Generate/Send buttons are in the right column, but the main controller is still the same as the original version.
![Preview](https://user-images.githubusercontent.com/42905588/227674599-21610711-7276-413c-aa36-cc5108e74dc3.png)

**Comment by thatjimupnorth** [comment]
I can see why you would do this and it's not like the original GUI is bad, it's just a little awkward. I do love how we can now grab the feet and hands however. That's brilliant. Thanks for all you're doing.
